use_frameworks!

platform :ios, '8.0'

target 'CYYPrivateHelloWorld_Example' do
  pod 'CYYPrivateHelloWorld', :path => '../'

  target 'CYYPrivateHelloWorld_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
